/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAiChatRouteImport } from './routes/api/ai.chat'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthSetupRouteImport } from './routes/api/auth/setup'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth/status'
import { Route as ApiMetricsSessionIdRouteImport } from './routes/api/metrics.$sessionId'
import { Route as ApiPtySessionIdRouteImport } from './routes/api/pty.$sessionId'
import { Route as ApiSftpDownloadRouteImport } from './routes/api/sftp/download'
import { Route as ApiSftpUploadRouteImport } from './routes/api/sftp/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSetupRoute = ApiAuthSetupRouteImport.update({
  id: '/api/auth/setup',
  path: '/api/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth/status',
  path: '/api/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsSessionIdRoute = ApiMetricsSessionIdRouteImport.update({
  id: '/api/metrics/$sessionId',
  path: '/api/metrics/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPtySessionIdRoute = ApiPtySessionIdRouteImport.update({
  id: '/api/pty/$sessionId',
  path: '/api/pty/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSftpDownloadRoute = ApiSftpDownloadRouteImport.update({
  id: '/api/sftp/download',
  path: '/api/sftp/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSftpUploadRoute = ApiSftpUploadRouteImport.update({
  id: '/api/sftp/upload',
  path: '/api/sftp/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/metrics/$sessionId': typeof ApiMetricsSessionIdRoute
  '/api/pty/$sessionId': typeof ApiPtySessionIdRoute
  '/api/sftp/download': typeof ApiSftpDownloadRoute
  '/api/sftp/upload': typeof ApiSftpUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/metrics/$sessionId': typeof ApiMetricsSessionIdRoute
  '/api/pty/$sessionId': typeof ApiPtySessionIdRoute
  '/api/sftp/download': typeof ApiSftpDownloadRoute
  '/api/sftp/upload': typeof ApiSftpUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/setup': typeof ApiAuthSetupRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/metrics/$sessionId': typeof ApiMetricsSessionIdRoute
  '/api/pty/$sessionId': typeof ApiPtySessionIdRoute
  '/api/sftp/download': typeof ApiSftpDownloadRoute
  '/api/sftp/upload': typeof ApiSftpUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/ai/chat'
    | '/api/auth/login'
    | '/api/auth/setup'
    | '/api/auth/status'
    | '/api/metrics/$sessionId'
    | '/api/pty/$sessionId'
    | '/api/sftp/download'
    | '/api/sftp/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/ai/chat'
    | '/api/auth/login'
    | '/api/auth/setup'
    | '/api/auth/status'
    | '/api/metrics/$sessionId'
    | '/api/pty/$sessionId'
    | '/api/sftp/download'
    | '/api/sftp/upload'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/ai/chat'
    | '/api/auth/login'
    | '/api/auth/setup'
    | '/api/auth/status'
    | '/api/metrics/$sessionId'
    | '/api/pty/$sessionId'
    | '/api/sftp/download'
    | '/api/sftp/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthSetupRoute: typeof ApiAuthSetupRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiMetricsSessionIdRoute: typeof ApiMetricsSessionIdRoute
  ApiPtySessionIdRoute: typeof ApiPtySessionIdRoute
  ApiSftpDownloadRoute: typeof ApiSftpDownloadRoute
  ApiSftpUploadRoute: typeof ApiSftpUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/setup': {
      id: '/api/auth/setup'
      path: '/api/auth/setup'
      fullPath: '/api/auth/setup'
      preLoaderRoute: typeof ApiAuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/status': {
      id: '/api/auth/status'
      path: '/api/auth/status'
      fullPath: '/api/auth/status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics/$sessionId': {
      id: '/api/metrics/$sessionId'
      path: '/api/metrics/$sessionId'
      fullPath: '/api/metrics/$sessionId'
      preLoaderRoute: typeof ApiMetricsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pty/$sessionId': {
      id: '/api/pty/$sessionId'
      path: '/api/pty/$sessionId'
      fullPath: '/api/pty/$sessionId'
      preLoaderRoute: typeof ApiPtySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sftp/download': {
      id: '/api/sftp/download'
      path: '/api/sftp/download'
      fullPath: '/api/sftp/download'
      preLoaderRoute: typeof ApiSftpDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sftp/upload': {
      id: '/api/sftp/upload'
      path: '/api/sftp/upload'
      fullPath: '/api/sftp/upload'
      preLoaderRoute: typeof ApiSftpUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthSetupRoute: ApiAuthSetupRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiMetricsSessionIdRoute: ApiMetricsSessionIdRoute,
  ApiPtySessionIdRoute: ApiPtySessionIdRoute,
  ApiSftpDownloadRoute: ApiSftpDownloadRoute,
  ApiSftpUploadRoute: ApiSftpUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
